name: blogspot
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  http: ^1.3.0
  provider: ^6.1.2
  retrofit: ^4.4.2
  shared_preferences: ^2.3.5
  cloudinary_dart: ^1.0.0
  cloudinary_api: ^1.0.0

dev_dependencies:
  build_runner:
  retrofit_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
